services:
  dicom-sender:
    container_name: dicom-sender
    image: registry.labspace.io.vn/dicom-sender:2.1
    ports:
      - "5001:5001"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - DEFAULT_AE_TITLE=DCMSRV
      - DEFAULT_HOST=X.X.X.X
      - DEFAULT_PORT=11112
      - CONNECT_TIMEOUT=5000
      - RESPONSE_TIMEOUT=30000
      - UPLOAD_FOLDER=/dicoms
      # - SERVER_NAME=yendungbgg
      # - TELEGRAM_BOT_TOKEN=123456789:ABC...
      # - TELEGRAM_CHAT_ID=-100123456789
    volumes:
      - ./logs:/app/logs
      - ./dicoms:/dicoms
    restart: unless-stopped
